#!/usr/bin/env python3
# sr FILE START END : print listing lines whose address is in [START, END)
import sys, re
f, a, b = sys.argv[1], int(sys.argv[2], 16), int(sys.argv[3], 16)
for line in open(f):
    m = re.match(r'\s+([0-9A-F]{4})\s', line)
    if not m:
        continue
    v = int(m.group(1), 16)
    if a <= v < b: print(line.rstrip()[:70])
